# Generated by Django 5.2 on 2025-05-18 04:11

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
                ('license_plate', models.CharField(max_length=15, unique=True)),
                ('transmission', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=100)),
                ('seating_capacity', models.IntegerField()),
                ('rental_price_wd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rental_price_wod', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='images/')),
                ('is_available', models.BooleanField(default=True)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=350, max_digits=10)),
                ('fuel_rate', models.DecimalField(decimal_places=2, default=40, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RentalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('payment_due_date', models.DateTimeField(default=datetime.datetime(2025, 5, 19, 4, 11, 53, 634615, tzinfo=datetime.timezone.utc))),
                ('payment_made', models.BooleanField(default=False)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_history', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.car')),
            ],
        ),
    ]
