# Generated by Django 5.2 on 2025-05-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalhistory',
            name='payment_due_date',
        ),
        migrations.RemoveField(
            model_name='rentalhistory',
            name='payment_made',
        ),
        migrations.AddField(
            model_name='rentalhistory',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
